language: node_js
node_js:
  - "10.15.3"
cache: yarn
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - libusb-1.0-0-dev
script:
  - npm run lint
  - npm run test
  - npm run build
